### ISSUE TITLE
PKL has no returns in text

### ISSUE THREAD

**Issue by mikekrause35pm** [sandflow/repkl#2]
Newly created PKLs do not have returns between lines. When opened in a text editor, the xml is not easily readable. Depending on the reader it may wrap into a block of text, or it may simply scroll offscreen to the right.

**Comment by palemieux** [comment]
@mikekrause35pm Try `pip install -i https://test.pypi.org/simple/ repkl`

**Comment by mikekrause35pm** [comment]
latest update appears to have no changes in PKL writing.
